<!doctype html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen"  href="/style.css">
    <title><?=$pagetitle?></title>
  </head>
  <body>
    <div id="main">	
      <div id="menuholder">
	<ul class="menu_list">
	  <?php foreach($menuentries as $page => $name) { ?>
	  <li class="menuitem"><a href="<?=$page?>"><?=$name?></a></li>
	  <?php } ?>
	</ul>
      </div>
      <div id="contentholder">
      <?=$content?>
      </div>
      <?php if(isset($sidebarContent)) {?>
      <div id="sidebar">
      <?=$sidebarContent?>
      </div>
      <?php } ?>
    </div>
  </body>
</html>
