<!doctype html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php if(isset($stylesheets)) {
    for($i = 0;$i < count($stylesheets);++$i) { ?>
    <link rel="stylesheet" type="text/css" media="screen"  href="<?=$stylesheets[$i]?>">
    <?php } }?>
    <?php if(isset($scripts)) {
    for($i = 0;$i < count($scripts);++$i) { ?>
    <script type="text/javascript" src="<?=$scripts[$i]?>"/>
    <?php } }?>
    <title><?=$pagetitle?></title>
  </head>
  <body>
    <div id="main">	
      <div id="menuholder">
	<ul class="menu_list">
	  <?php foreach($menuentries as $page => $name) { ?>
	  <li class="menuitem"><a href="<?=$page?>"><?=$name?></a></li>
	  <?php } ?>
	</ul>
      </div>
      <div id="contentholder">
      <?=$content?>
      </div>
      <?php if(isset($sidebarcontent)) {?>
      <div id="sidebar">
      <?=$sidebarcontent?>
      </div>
      <?php } ?>
    </div>
  </body>
</html>
