<?php if(!$loggedin) { ?>
<form method="post">
	    <table>
	      <tr>
		<td><label for="username">Username</label></td>
		<td><input type="text" name="username" id="username" value="<?php if(isset($defaultUsername)) echo($defaultUsername);?>"/></td>
	      </tr>
	      <tr>
		<td><label for="password">Passwort</label></td>
		<td><input type="password" name="password" id="password"/><input type="hidden" name="ref" id="ref" value = <?=$referer?></td>
	      </tr>
	      <tr><td><button type="submit">Login</button></td></tr>
	    </table>
	  </form>
<?php } ?>
<?php if(isset($errmsg)) { ?>
<div id = "infoerr">
<?php if($errmsg == "errUserPwd") {?>
Anmeldung gescheitert. Bitte überprüfen Sie die Schreibweise von Benutzernamen und Passwort.
<?php } else if($errmsg == "errDbCon") {?>
Es trat ein Fehler bei der Datenbankverbindung auf. Bitte versuchen Sie es später noch einmal.
<?php } else if($errmsg == "errLoggedInAlready") {?>
Sie sind bereits angemeldet. Bitte melden Sie zuerst mit dem Link links im Menü ab.
<?php } else if($errmsg == "errLoggedOutAlready") {?>
Sie sind bereits abgemeldet.
<?php } ?>
</div>
<?php } ?>

<?php if(isset($infomsg)) { ?>
<div id = "infosucc">
<?php if($infomsg == "infLoggedIn") {?>
Anmeldung erfolgreich.
<?php } else if($infomsg == "infLoggedOut") {?>
Sie sind jetzt abgemeldet.
<?php } else if($infomsg == "infLoggedInAlready") {?>
Sie sind bereits angemeldet. Um auf einen anderen Benutzer zu wechseln, bitte melden Sie sich mit dem Link links im Menü ab.
<?php } ?>
</div>
<?php } ?>
<br><br>
<a href="<?=$referer?>">Zurück zur vorherigen Seite</a>
