<h1>Details zu Spot <?=$spotname?></h1>
<table>
<tr><td>Name</td><td><?=$spotname?></td></tr>
<tr><td>Ort</td><td><?=$spotloc?></td></tr>
<tr><td>Beschreibung</td><td><?=$spotdesc?></td></tr>
<tr><td>Koordinaten</td><td><?=$lat?>; <?=$lon?></td></tr>

<?php if(isset($images)) { foreach($images as $img){ ?>
<tr><td colspan="2"><img alt="Bild von <?=$spotname?>" src="/images/<?=$img["filename"]."/".$img["filename_original"]?>"></td></tr>
<?php }} else { ?>
<tr><td colspan="2">Zu diesem Spot wurde kein Bild gespeichert.</td></tr>
<?php } ?></td></tr>

<?php if(isset($nearby)) { ?>
<tr><td colspan="2">In der Nähe: (gefunden in <?=$time?>ms)</td></tr>
<?php foreach($nearby as $nearname => $neardist){ ?>
<tr><td><a href="/myspot/<?=$nearname?>"><?=$nearname?></a></td><td><?=$neardist?> km</td></tr>
<?php } } else { ?>
<tr><td colspan="2">Keine Spots in der Nähe.</td></tr>
<?php } ?></td></tr>

<?php if($loggedin) {?>
<tr><td colspan="2"><a href="edit/">Ändern</a></td></tr>
<tr><td colspan="2"><a href="delete/">Löschen</a></td></tr>
<?php } else { ?>
<tr><td colspan="2">Sie sind nicht angemeldet. Bitte <a href="/login/">melden Sie sich an</a>, um Spots zu bearbeiten oder zu löschen.</td></tr>
<?php } ?>
</table>
