	  <h1><?=$title?></h1>
	  <?php if(count($spotdata) > 0) { ?>
	  <table id='datatbl'>
	    <tr class='dataheadline'>
	      <td class='dataheadcell'>Spotname</td>
	      <td><td></td>
	    </tr>
	    <?php foreach($spotdata as $attribs) { ?>
	    <tr class='dataline'>
              <td class='datacell'><?=$attribs["name"]?></td></tr>
	    <?php } ?>
	  </table><br><br>
	  Angezeigt werden Spots <?=$spotNrStart?> bis <?=$spotNrEnd?> von insgesamt <?=$spotCount?>.<br />
	  <?php } else { ?>
	  Keine Spots gefunden.
	  <?php } ?>
	  
	  <?php if(isset($showPaginator)) {?>
	<div id="paginator">
	<?php for($i = 0; $i < $pagPages;++$i) {?>
	<a href = "?page=<?=$i?>"><?=$i?></a> 
	<?php }?>
	</div>
	<?php }?>
