<h1>Details zu Spot <?=$spotname?></h1>
<table>
<tr><td>Name</td><td><?=$spotname?></td></tr>
<tr><td>Ort</td><td><?=$spotloc?></td></tr>
<tr><td>Beschreibung</td><td><?=$spotdesc?></td></tr>
<tr><td>Bild</td><td>
<?php if(isset($spotimg) && $spotimg != "") { ?>
<img alt="Bild von <?=$spotname?>" src="/images/<?=$spotimg?>">
<?php } else { ?>
Zu diesem Spot wurde kein Bild gespeichert.
<?php } ?></td></tr>
</table>