<h1><?=$title?></h1>
<div id="searchbar">
	<form method="get">
		<input type="text" name="search" id="search" <?php if(isset($search)){?>value="<?=$search?>"<?php } ?>/>
		<button type="submit">Suchen</button>
	</form>
</div>
<div id="spotlist">
	<?php if(count($spotdata) > 0) { ?>
	<table id='datatbl'>
	<tr class='dataheadline'>
	<td class='dataheadcell'>Spotname</td>
	<td><td></td>
	</tr>
	<?php foreach($spotdata as $attribs) { ?>
	<tr class='dataline'>
	<td class='datacell'><a href="/myspot/<?=$attribs["name"]?>/"><?=$attribs["name"]?></a></td></tr>
	<?php } ?>
	</table><br><br>
	Angezeigt werden Spots <?=$spotNrStart?> bis <?=$spotNrEnd?> von insgesamt <?=$spotCount?>, in <? echo(round($time,3)); ?> ms.<br />
	<?php } else { ?>
	Keine Spots gefunden.
	<?php } ?>
</div>
<?php if(isset($showPaginator)) {?>
<div id="paginator">
	<?php if (isset($search)) { ?>
	<a href = "?search=<?=$search?>&page=1">1</a>
	<?php } else { ?>
	<a href = "?page=1">1</a>
	<?php } for($i = $currPagVal - 10; $i <= $currPagVal + 10 ;++$i) {?>
	<?php if($i > 1 && $i < $pagPages){ ?>
	<?php if (isset($search)) { ?>
	<a href = "?search=<?=$search?>&page=<?=$i?>"><?=$i?></a>
	<?php } else { ?>
	<a href = "?page=<?=$i?>"><?=$i?></a>
	<?php }}}
	if($currPagVal + 11 < $pagPages) { ?>
	 ... 
	<?php }
	if (isset($search)) { ?>
	<a href = "?search=<?=$search?>&page=<?=$pagPages?>"><?=$pagPages?></a>
	<?php } else { ?>
	<a href = "?page=<?=$pagPages?>"><?=$pagPages?></a>
	<?php } ?>
</div>
<?php }?>
<?php if(isset($infomsg)) {?>
	<div id="infomsg"><?=$infomsg?></div>
<?php } ?>
