<!doctype html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen"  href="/style.css">
    <link rel="stylesheet" type="text/css" media="screen"  href="/stylems.css">
    <title><?=$title?></title>
  </head>
    <body>
    <div id="main">
      
      <div id="menuholder">
	<ul class="menu_list">
	  <?php foreach($menuentries as $curr => $currname) { ?>
	  <li class="<?php if(basename($curr,'.php') == basename(__FILE__,'.phtml')) echo('current '); ?>menuitem"><a href="<?=$curr?>"><?=$currname?></a></li>
	  <?php } ?>
	</ul>
      </div>
	<div id="contentholder">
	  <h1><?=$title?></h1>
	  <?php if($fatalerror) { ?>
	  <div id ="fatalerrormsg"><?=$fatalerrormsg?></div>
	  <?php } else { ?>
	  <?php if(count($data) > 0) { ?>
	  <table id='datatbl'>
	    <tr class='dataheadline'>
	      <td class='dataheadcell'>Name</td>
	      <td class='dataheadcell'>Ort</td>
	      <td class='dataheadcell'>Beschreibung</td>
	      <td><td></td>
	    </tr>
	    <?php foreach($data as $item=>$attribs) { ?>
	    <tr class='dataline'>
              <td class='datacell'><?=$attribs["name"]?></td>
              <td class='datacell'><?=$attribs["location"]?></td>
              <td class='datacell'><?=$attribs["description"]?></td>
              <td class='datacell'><a href='#' onclick='document.getElementById("name").setAttribute("value","<?=$attribs["name"]?>");document.getElementById("loc").setAttribute("value","<?=$attribs["location"]?>");document.getElementById("desc").value="<?=$attribs["description"]?>";'>Ändern</a></td>
              <td class='datacell'><a href='myspot.php?delete=<?=$attribs["name"]?>'>Löschen</a></td></tr>
	    <?php } ?>
	  </table><br><br>
	  <?php } else { ?>
	  Im Moment sind keine Spots gespeichert.
	  <?php } ?>

	  <?php if($infomsg != "") { ?>
	  <div id = <?=$infotype?>><?=$infomsg?></div><br />
	  <?php } ?>

	  Anzahl gespeicherte Spots: <?=$spotcount?><br />
	  <br><br>
	  <form method="get">
	    <table>
	      <tr>
		<td><label for="name">Name</label></td>
		<td><input type="text" name="name" id="name"/></td>
	      </tr>
	      <tr>
		<td><label for="loc">Ort</label></td>
		<td><input type="text" name="loc" id="loc"/></td>
	      </tr>
	      <tr>
		<td><label for="desc">Text</label></td>
		<td><textarea rows="10" cols="30" name="desc" id="desc"></textarea></td>
	      </tr>
	      <tr><td></td><td><button type="submit">Speichern</button></td></tr>
	    </table>
	  </form>
	  <?php } ?>
	</div>
    </div>
  </body>
</html>
