<h1><?=$title?></h1>
<script type="text/javascript">
function submit() {
	if(document.forms["fmain"]["name"].value == ""||document.forms["fmain"]["name"].value == null) {
		alert("Feld Name darf nicht leer sein.");
	}
	return false;
}
</script>
<form name="fmain" enctype="multipart/form-data" action="/myspot/" method="post" onsubmit="alert('men')";>
<table>
<tr><td><label for="name">Name</label></td><td>
<?php if($action=="new") {?><input type="text" name="name" id="name" required value="<?php if(isset($editspotname)) echo($editspotname);?>" /><?php }
else if ($action=="edit") {?> <?=$editspotname?><input type="hidden" name="name" id="name" value="<?php if(isset($editspotname)) echo($editspotname);?>" />
<?php }?>
</td></tr>
<tr><td><label for="loc" >Ort</label></td><td><input type="text" name="loc" id="loc" value="<?php if(isset($editspotloc)) echo($editspotloc);?>" /></td></tr>
<tr><td><label for="desc">Beschreibung</label></td><td><input type="text" name="desc" id="desc" value="<?php if(isset($editspotdesc)) echo($editspotdesc);?>" /></td></tr>
<tr><td><label for="img">Bild</label></td><td><input type="file" name="img" id="img" accept="image/*" /></td></tr>
<tr><td><label for="long">Längengrad</label></td><td><input type="text" required name="long" id="long" value="<?php if(isset($editspotlong)) echo($editspotlong);?>" /></td></tr>
<tr><td><label for="lat">Breitengrad</label></td><td><input type="text" required name="lat" id="lat" value="<?php if(isset($editspotlat)) echo($editspotlat);?>" /></td></tr>
<tr><td colspan="2"><input type="submit" value="Abschicken"/> <input type="hidden" name = "action" id="action" value="<?=$action?>"/></td></tr>
</table>
</form>
