<!doctype html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen"  href="/style.css">
    <link rel="stylesheet" type="text/css" media="screen"  href="/stylems.css">
    <title><?=$title?></title>
  </head>
    <body>
    <div id="main">
      <div id="menuholder">
	<ul class="menu_list">
	  <?php foreach($menuentries as $curr => $currname) { ?>
	  <li class="<?php if(basename($curr,'.php') == basename(__FILE__,'.phtml')) echo('current '); ?>menuitem"><a href="<?=$curr?>"><?=$currname?></a></li>
	  <?php } ?>
	</ul>
      </div>
	<div id ="login">
		<?php if($loggedin) {>
			<button type="button">Ausloggen</button>
		<?php } else { ?>
			<form method="get">
				<input type="text" name="username" id="username"/>
				<input type="text" name="password" id="password"/>
				<button type="submit">Einloggen</button>
			</form>
		<?php } ?>
	</div>

	<div id="searchbar">
	<form method="get">
		<input type="text" name="search" id="search"/>
		<button type="submit">Suchen</button>
	</form>

	</div>
	<div id="contentholder">
	  <h1><?=$title?></h1>
	  <?php if($fatalerror) { ?>
	  <div id ="fatalerrormsg"><?=$fatalerrormsg?></div>
	  <?php } else { ?>
	  <?php if(count($data) > 0) { ?>
	  <table id='datatbl'>
	    <tr class='dataheadline'>
	      <td class='dataheadcell'>Name</td>
	      <td class='dataheadcell'>Ort</td>
	      <td class='dataheadcell'>Beschreibung</td>
	      <td><td></td>
	    </tr>
	    <?php foreach($data as $item=>$attribs) { ?>
	    <tr class='dataline'>
              <td class='datacell'><?=$attribs["name"]?></td>
              <td class='datacell'><?=$attribs["location"]?></td>
              <td class='datacell'><?=$attribs["description"]?></td>
              <td class='datacell'><a href='#' onclick='document.getElementById("name").setAttribute("value","<?=$attribs["name"]?>");document.getElementById("loc").setAttribute("value","<?=$attribs["location"]?>");document.getElementById("desc").value="<?=$attribs["description"]?>";'>Ändern</a></td>
              <td class='datacell'><a href='myspot.php?delete=<?=$attribs["name"]?>'>Löschen</a></td></tr>
	    <?php } ?>
	  </table><br><br>
	  <?php } else { ?>
	  Im Moment sind keine Spots gespeichert.
	  <?php } ?>

	  Anzahl gespeicherte Spots: <?=$spotcount?><br />

	  <?php } ?>
	</div>
	<div id="paginator">
		<ul class="paginator">
			  <?php for($i = 1; $i <= $groupcount; $i = $i+1){ ?>
			  <li class="<?php if($i == $currentpage) echo('current '); ?>paginatoritem"><a href="myspot.php?start=<?=$i ?>"><?=$i ?></a></li>
			  <?php } ?>
		</ul>
	</div>
    </div>
  </body>
</html>
